heat_template_version: 2013-05-23

description: Creates a simple instance 

parameters:
  instance_name:
    type: string
    description: name of the instance to create
    default: instance0
  image:
    type: string
    description: image from which to boot
    default: OSP-5-RHEL-7-Template
  key_name:
    type: string
    description: ssh key for access
  security_group_id:
    type: string
    description: security group to use for instance
    default: f0fd744b-a49b-4ecd-9146-8d6752942cb6
  private_network_id:
    type: string
    description: UUID of private network
    default: c6807c63-2d02-40fd-b7ad-019bbf2bd9df
  public_network_id:
    type: string
    description: UUID of floating ip network
    default: eb94d7e2-94be-45ee-bea0-22b9b362f04f

resources:
  NODE:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: m1.large
      name: { get_param: instance_name }
      networks:
        - port: { get_resource: instance0_port0 }
  instance0_port0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network_id }
      security_groups:
        - { get_param: security_group_id }

outputs:
  instance0_private_ip:
    description: IP address of instance0 in private network
    value: { get_attr: [ { get_param: instance_name }, first_address ] }

